version: "3"

networks:
  backend-network:  # User-defined bridge network for the backend services
    driver: bridge

services:
  server-container:
    image: ubuntu_llama_image
    container_name: ubuntu_llama_container_server
    working_dir: /home/llama.cpp_dir/
    build:
      context: .
      dockerfile: DockerfileUbuntu.dockerfile
    networks:
      - backend-network 
    ports:
      - "8080:8080"
      - "3838:3838"

  ttyd-container:
    image: ubuntu_llama_image
    container_name: ubuntu_llama_container_ttyd
    working_dir: /home/llama.cpp_dir/
    build:
      context: .
      dockerfile: DockerfileUbuntu.dockerfile
    networks:
      - backend-network 
    ports:
      - "7681:7681"
    command: ttyd --writable bash -c "./runprogram.sh"


